clearpathrobotics/navigation

base_local_planner/src/costmap_model.cpp
costmap_2d/include/costmap_2d/inflation_layer.h
costmap_2d/plugins/inflation_layer.cpp
costmap_2d/plugins/static_layer.cpp
global_planner/include/global_planner/dijkstra.h
global_planner/include/global_planner/planner_core.h
global_planner/src/dijkstra.cpp
global_planner/src/planner_core.cpp
move_base/include/move_base/move_base.h
move_base/src/move_base.cpp

This is the aggregation of all the fixes I have made to the navigation stack. After we do a internal review I will push them upstream one at a time.
I combined them all since they are each fairly simple and I didn't want to make 4 reviews but I can split them if you want.

Fixes to navigation found from long term testing

---

costmap_2d/include/costmap_2d/axis_aligned_bounding_box.h
costmap_2d/include/costmap_2d/costmap_2d.h
costmap_2d/include/costmap_2d/dynamic_algorithm_select.h
costmap_2d/include/costmap_2d/layer.h
costmap_2d/include/costmap_2d/obstacle_layer.h
costmap_2d/plugins/footprint_layer.cpp
costmap_2d/plugins/inflation_layer.cpp
costmap_2d/plugins/obstacle_layer.cpp
costmap_2d/plugins/static_layer.cpp
costmap_2d/src/axis_aligned_bounding_box.cpp
costmap_2d/src/costmap_2d.cpp

Layer current_ corrections
Obstacle layer memory

Inflation Layer Fixes

---

costmap_2d/plugins/obstacle_layer.cpp
costmap_2d/src/layered_costmap.cpp

Mutex code beautified in layered_costmap

Infinite loop in debug bailout removed from obstacle layer.

---

costmap_2d/cfg/InflationPlugin.cfg
costmap_2d/cfg/ObstaclePlugin.cfg
costmap_2d/include/costmap_2d/inflation_layer.h
costmap_2d/include/costmap_2d/obstacle_layer.h
costmap_2d/plugins/inflation_layer.cpp
costmap_2d/plugins/obstacle_layer.cpp

Inflation method and obstacle forget related parameters are now controlled via dynamic reconfigure.

Moved inflation and obstacle dynamic parameters from the parameter server to dynamic reconfigure.

---

costmap_2d/plugins/inflation_layer.cpp

as inflation window can now change from one call to the next.
Also changed window check from not equal to less than.

Removed seen size is wrong spam

---

costmap_2d/include/costmap_2d/costmap_2d_ros.h
costmap_2d/include/costmap_2d/layered_costmap.h
costmap_2d/plugins/inflation_layer.cpp
costmap_2d/src/costmap_2d_ros.cpp
costmap_2d/src/layered_costmap.cpp

This set of changes basically adds a param to allow move_base to receive footprint updates without affecting the inflation layer.
@jasonimercer @skaynama @servos

Core2005 static inflation radius

---

move_base/src/move_base.cpp

Fixed a bug that could cause recursive PLANNING-CLEARING state change. And another that would prevent move_base from going into CONTROLLING even when a valid path was found.
@servos @jasonimercer @p6chen

CORE-2029: Fixed a few issues with move_base's state machine

---

costmap_2d/src/costmap_2d_ros.cpp

As requested by the infrastructure team.

CORE-2098 throttle tf complaint

---

costmap_2d/include/costmap_2d/dynamic_algorithm_select.h
costmap_2d/src/axis_aligned_bounding_box.cpp
costmap_2d/src/dynamic_algorithm_select.cpp

Minor changes to generalize timers to work on OSX

Minor changes to generalize timers to work on OSX

---

costmap_2d/include/costmap_2d/obstacle_layer.h
costmap_2d/plugins/obstacle_layer.cpp

Add max_range measurements to laser scans to clean out free space

---

costmap_2d/include/costmap_2d/static_layer.h

I want to make a child class of static layer so I need its members to be protected not private.
@jasonimercer @skaynama

Make member of static layer protected not private

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp

@jasonimercer @p6chen @skaynama

Fixing incorrectly assigned goal/plan pairs

---

costmap_2d/plugins/static_layer.cpp

FYI @jasonimercer @p6chen @skaynama

Fixing potential deadlock during map loading

---

move_base/src/move_base.cpp
nav_core/include/nav_core/base_global_planner.h

and documented requirement of lower level to lock the map as required.
@p6chen 
@servos 
@ayrton04 
@chandel01 
@skaynama

Removed planning related costmap lock from higher level

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp
nav_core/include/nav_core/recovery_behavior.h

FYI @jasonimercer @skaynama @p6chen. See my forthcoming PRs for this ticket for more information.

Adding service calls the indicate that recovery execution has completed

---

costmap_2d/include/costmap_2d/layer.h
costmap_2d/include/costmap_2d/layered_costmap.h
costmap_2d/include/costmap_2d/obstacle_layer.h
costmap_2d/plugins/obstacle_layer.cpp
costmap_2d/src/layer.cpp
costmap_2d/src/layered_costmap.cpp

This change is required for CORE-2631. We'll need to be able to disable the obstacle memory information.
@jasonimercer @p6chen

Adding service for clearing obstacle memory

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp
nav_core/include/nav_core/base_global_planner.h
nav_core/include/nav_core/base_local_planner.h
nav_core/include/nav_core/recovery_behavior.h

Give recovery behaviours a method to access to current local or global planner.

---

nav_core/include/nav_core/recovery_behavior.h

Making set fetch functions virtual

---

move_base/src/move_base.cpp

Already reviewed in the other pull request. Going to merge.

CORE-3019: Fix for excessive logging attempt #2!!!

---

costmap_2d/include/costmap_2d/inflation_layer.h
costmap_2d/plugins/inflation_layer.cpp

@skaynama @p6chen 
(FYI @jasonimercer)
Note that I am merging this into the indigo-devel-cpr-costmaps branch.

Bringing inflation in line with upstream

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp

@jasonimercer @skaynama @servos

Action Server Feedback on Timer

---

costmap_2d/plugins/inflation_layer.cpp

Change inflation back to thresholding based static inflation.

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp
nav_core/include/nav_core/base_local_planner.h

Only revert recovery if pose has changed from recovery pose.

---

costmap_2d/include/costmap_2d/costmap_2d_ros.h
costmap_2d/include/costmap_2d/layer.h
costmap_2d/include/costmap_2d/layered_costmap.h
costmap_2d/include/costmap_2d/obstacle_layer.h
costmap_2d/plugins/obstacle_layer.cpp
costmap_2d/src/costmap_2d_ros.cpp
costmap_2d/src/layered_costmap.cpp

CORE-3930: Added topic that can be used to set footprint padding.

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp
nav_core/include/nav_core/base_global_planner.h
nav_core/include/nav_core/base_local_planner.h
nav_core/include/nav_core/base_planner.h
nav_core/include/nav_core/goal_tolerances.h
nav_core/include/nav_core/goal_tolerances_aware.h
nav_core/include/nav_core/nav_goal_manager.h
nav_core/include/nav_core/recovery_behavior.h

Created a common parent class for base_local_planner and base_global_planner.
Created a goal tolerance object.
Added goal tolerance shared pointer to new common parent class.
Populate goal tolerance object in move_base.
@skaynama  @p6chen

Make planners aware of goal tolerances.

---

costmap_2d/src/observation_buffer.cpp

Adds a check to the wait for transform. This stops the "This error should never happen" message from popping up due to a race condition at startup where the TF might not be published yet.
A better solution should probably be found to address the race to begin with but for now this just stops the scary error from showing up.
@jasonimercer @skaynama

Add check on waitForTF in observation buffer

---

move_base/CMakeLists.txt
move_base/include/move_base/move_base.h
move_base/package.xml
move_base/src/move_base.cpp
move_base_msgs/CMakeLists.txt
move_base_msgs/action/AugmentedMoveBase.action
move_base_msgs/package.xml

Part of a set of 5 PRs to enable arbitrary data in a move_base goal. 
@skaynama @p6chen @abencz

Define and use augmented move_base goal

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp
nav_core/include/nav_core/base_global_planner.h
nav_core/include/nav_core/base_local_planner.h
nav_core/include/nav_core/nav_status.h

Adds ability for global planner to return a status. Move_base aborts if the status returned is a fatal error.

CORE-3602: Abort when end goal is not valid 

---

move_base/src/move_base.cpp

message type fix

---

move_base/include/move_base/move_base.h
move_base/src/move_base.cpp
nav_core/include/nav_core/goal_tolerances.h

and populate them via goal attributes
@skaynama @p6chen

Add relative goal tolerances to the goal_tolerance object 

---

nav_core/include/nav_core/goal_tolerances.h

Fix for using sincos with OSX
@jasonimercer

Fix for sincos for OSX

---

nav_core/include/nav_core/goal_tolerances.h

@p6chen @skaynama @schopra01 
Fixes wobble on goal 
CORE-4390

Treat 2pi periodicity properly in yaw tolerance decisions.

---

nav_core/include/nav_core/nav_status.h

Used to make preemption decisions cleaner. Preempt will return CANCEL
@skaynama  @p6chen  @schopra01 
FYI: @stephmcarthur

CORE 4461 Added CANCEL status
