- move_base/src/move_base.cpp
Currently move_base deadlocks when you try to reconfigure the planner due to trying to take the planner_mutex_ twice.
> Stop deadlock when reconfiguring planner

- costmap_2d/src/costmap_2d.cpp
Without this change a crash is possible if the underlying map is changed while layer actions are being applied.
> Added bounds checks to memset. CORE-1654

- costmap_2d/src/costmap_2d.cpp
I mistakenly thought xn/yn were the number of things in the x or y direction but they are part of the limits as in x_{0} to x_{n} inclusively. 
This required the same "inclusive" style bounds checks on the upper bound as the lower bound.
> Tightened limit on upper range.

- costmap_2d/plugins/inflation_layer.cpp
Inflation used to do this and I removed it. This puts things back the way they were. Without this it's possible to have large chunks missing on large maps.
> Marked full map to be updated on need_reinflation in InflationLayer

- costmap_2d/plugins/obstacle_layer.cpp
- costmap_2d/plugins/static_layer.cpp
- costmap_2d/src/costmap_2d.cpp
- costmap_2d/src/costmap_layer.cpp
- costmap_2d/src/layered_costmap.cpp
This adds protection around areas where the costmap is being read from or written to. Before this it was easy to trigger a crash by quickly loading maps of various sizes. The costmap plugins would operate on data that would change size and end up seg-faulting. 
Note: The mutexes are now recursive mutexes so locking on the same one in a single thread is OK.
@skaynama 
@servos 
@paulbovbel
> Core 1735 map load mutexes

- costmap_2d/plugins/inflation_layer.cpp
The layered costmap takes the minimum and maximum updated boundaries across all its member layers when updating its own boundaries. This prevents wasted computation but still ensures that all changes in constituent costmaps are reflected in the layered map. In the case of the inflation layer, if the inflation has never happened, the values in updateBounds should be set to the (-infinity, -infinity); (+infinity, +infinity), thereby forcing the entire layered costmap to update. This was attempted, but the code was using std::numeric_limits<double>::min() for -inifinity. For integer data types, this would work, but for doubles (the type being used), it returns the smallest positive value, which is a fraction larger than 0. This meant that we would only update the map from the map's origin to …
> Fixing minimum boundary value in the inflation layer's updateBounds method

- costmap_2d/cfg/ObstaclePlugin.cfg
- costmap_2d/include/costmap_2d/obstacle_layer.h
- costmap_2d/plugins/obstacle_layer.cpp
This PR fixes a regression where the code responsible for forgetting observations was not used if the pose confidence wasn't 1.0. 
Additions were made to allow proper clearing of old observations even when the robot is moving and discretization error could be a problem. This was done by clearing the internal buffer and only writing points we either see or remember.
> Core 1788 obstacle pose confidence

- costmap_2d/plugins/inflation_layer.cpp
Before this you could cause a crash by opening rqt/dynamic reconfigure, going to the global inflation layer and changing the radius.
> Added mutex so dynamic reconfigure cannot change memory until the plugin has finished running.

- move_base/include/move_base/move_base.h
- move_base/src/move_base.cpp
Caches global planner instances to avoid initialization.
@skaynama @jasonimercer @servos
> Added a cache for global planner plugin 

- costmap_2d/plugins/inflation_layer.cpp
Our recovery behavior has been failing due to this bug. The recovery behavior will call clearCostmapService which in turn calls resetLayers() in costmap2DRos. This ends up re-initializing each plugin layer. 
However, in Inflater_Layer, we set current_ = false during the initialization. Thus, after recovery, the planner will attempt to call move_base::makePlan, which checks each costmap layer for current_ = true. Since this fails, the planning will fail before even reaching SBPL. This is why our recovery should in theory never work atm, and why after failing the recovery, we can't issue a new path even when the robot is moved into the open.
@skaynama @jasonimercer
> Fix for planner failing after recovery behavior is executed.

- costmap_2d/plugins/obstacle_layer.cpp
> Use footprint to invalidate remembered obstacles when footprint clearing.

- base_local_planner/src/odometry_helper_ros.cpp
Makes it so that I can use getOdom() to get the current pose as well.
@skaynama @jasonimercer
> Make odomHelper copy the whole odometry message

- costmap_2d/include/costmap_2d/inflation_layer.h
- costmap_2d/include/costmap_2d/layer.h
- costmap_2d/include/costmap_2d/obstacle_layer.h
- costmap_2d/include/costmap_2d/static_layer.h
- costmap_2d/plugins/inflation_layer.cpp
- costmap_2d/plugins/obstacle_layer.cpp
- costmap_2d/plugins/static_layer.cpp
- costmap_2d/src/layer.cpp
- costmap_2d/src/layered_costmap.cpp
FYI @skaynama @p6chen. We are apparently removing LayerActions, so for compatibility with our other changes, I removed any methods that make use of them here. This branch is needed to work with the other internal repos I've been changing. Note that I am merging into a "catch-all" branch instead of indigo-devel for now.
@jasonimercer, feel free to ignore. Just tagging you so you're aware when you return.
> Getting rid of LayerActions

- move_base/src/move_base.cpp
As a result strategy_manager would never know of the failed status of move_base.
I noticed that in certain scenarios (e.g. when an obstacle is placed on top of the goal) ```recovery_index_``` would prematurely get reset to 0. And so since ```recovery_index_``` would never exceed the recovery count the goal would never get aborted. This is bad because strategy_manager (while tasked to continuously resend the same goal for a period of time) needs to be made aware that we failed to get to the goal on these attempts.
The reason this happened is because in one of our recoveries we disable the obstacle_layer and so planning would succeed and the if block would get executed. Re-enabling the obstacle_layer immediatelt would cause the state machine to go into recovery directly from …
> CORE-3041: Removed logic that could prevent goal from ever being aborted

- move_base/include/move_base/move_base.h
- move_base/src/move_base.cpp
- nav_core/CMakeLists.txt
- nav_core/include/nav_core/base_global_planner.h
- nav_core/include/nav_core/base_local_planner.h
- nav_core/include/nav_core/nav_goal.h
- nav_core/include/nav_core/nav_goal_manager.h
- nav_core/include/nav_core/recovery_behavior.h
Adding a mechanism to share the validity/activeness of the current goal so that planners and recovery strategies can stop running.
> Core 3163 move base goal manager

- move_base/include/move_base/move_base.h
- move_base/src/move_base.cpp
Registering custom callback with simple action server so we can preempt even during moving recoveries. 
@skaynama @p6chen
> Custom preempt callback in move_base

- move_base/src/move_base.cpp
Checking for null ptrs from the action server.
Changed preempt to set current goals as inactive, allowing new goals to filter in later.
> CORE-3682-null-ptr-check

- base_local_planner/include/base_local_planner/costmap_model.h
- base_local_planner/src/costmap_model.cpp
including:
- footprint perimeter
- center point check
- an X in the footprint
- a diamond in the footprint
- check every pixel
- combinations of any of the above
The default action is to do a footprint perimeter check, the center point, the diamond plus the X check which reproduces the current checks done in cpr_pathtracker (with the explicit diamond code removed). 
A follow-up PR for pathtracker will be provided that removes the explicit diamond code and use the dense footprint checks for the 0th and 1st footprints.
@skaynama  @p6chen
> Add the ability to do custom footprint checks

- move_base/src/move_base.cpp
Ensures the recoveries don't get cleared while it's possible to run them in another thread
@skaynama  @servos
> Moved recovery clear to the end of the destructor

- move_base/include/move_base/move_base.h
- move_base/src/move_base.cpp
- nav_core/include/nav_core/goal_tolerances_aware.h
Made move_base a goal_tolerances aware object and connected it's goal_tolerances with planners and trackers.
@skaynama  @p6chen
> Allow goal tolerances aware objects to propagate updates to other objects.

- move_base/include/move_base/move_base.h
- move_base/src/move_base.cpp
Sample error message:
[ERROR] [/move_base] [1464289635.268616707, 266.859000000]: move_base: Aborting on goal because it was sent too soon after the last goal 0.46s < 0.5s
@skaynama @servos 
FYI @p6chen
> Added minimum time between goals. Abort if time is too small.

- move_base/src/move_base.cpp
Ensures a stop happens before recovery cleanup
@skaynama @p6chen
> Publish zero cmd_vel earlier in the resetState method.

- costmap_2d/include/costmap_2d/inflation_layer.h
- costmap_2d/plugins/inflation_layer.cpp
- costmap_2d/test/inflation_tests.cpp
https://github.com/ros-planning/navigation/pull/478
"When marking before adding to the priority queue, it was possible to
underestimate the cost of a cell."
@p6chen @jasonimercer
> CORE-4296: Brought in bug fix 478 in the inflation layer from upstream

- move_base/include/move_base/move_base.h
- move_base/src/move_base.cpp
Before this is was possible to get the action server into a bad state with fast abort cycles now possible with the abort-when-planning-into-wall code. Strategy management would lock up.
Better solution will be CORE-4329.
@p6chen @abencz
> CORE-4311 Refactored abort code and introduced abort throttling.

- move_base/src/move_base.cpp
CORE-4449
@schopra01 @skaynama @p6chen
> On move_base shutdown, stop planning thread before deleting the costmaps and layers.

- move_base/include/move_base/diagnostic_publisher.h
- move_base/src/diagnostic_publisher.cpp
The diagnostic publisher could be called from multiple threads in move_base simultaneously, corrupting the internal state and crashing move_base. 
Without the namespace, some loaded libraries that share the diagnostic publisher code would crash as we are changing the size of the object. The namespace ensures this version of the publisher is treated uniquely wrt other publishers. (Should collect the publisher code in a common place).
@skaynama @p6chen @schopra01 
FYI: @stephmcarthur
> Added namespace and mutex to the move_base diagnostic publisher.
